language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

script:
  - pep8 pybots/
  - coverage run --source=pybots test.py

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pep8

after_success: coveralls

branches:
  only:
    - master

before_script:
  - "pep8 --ignore=E501 pybots" # ignore too long lines