language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

script:
  - python test.py
  - coverage run --source=pybots test.py

install:
  - pip install -r requirements.txt
  - pip install coveralls

after_success: coveralls

branches:
  only:
    - master

