language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

script:
  - coverage run --source=pybots test.py

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pep8
  - "if [[ $TRAVIS_PYTHON_VERSION != '3.4' ]]; then travis_retry pip install enum; fi"

after_success: coveralls

branches:
  only:
    - master

before_script:
  - "pep8 --ignore=E501,E731 pybots" # ignore too long lines, lambda assigning

matrix:
  allow_failures:
    - python: "3.2"
    - python: "3.3"
    - python: "3.5"